version: '3.8'

services:
  frontend:
    build: 
      context: ./url-shortener-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Map to port 80 for production
    depends_on:
      - backend
    environment:
      - BACKEND_API_URL=http://backend:8080

  backend:
    build: 
      context: ./url-shortener-backend
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://urlapp:your_password_here@mongodb:27017/urlshortener
      - SPRING_DATA_MONGODB_DATABASE=urlshortener
      - APP_BASE_URL=http://localhost:8081/

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./url-shortener-backend/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_DATABASE=urlshortener
      - MONGO_INITDB_ROOT_USERNAME=urlapp
      - MONGO_INITDB_ROOT_PASSWORD=your_password_here

volumes:
  mongodb_data: 