services:
  web:
    build: .
    ports:
      - "80:80"
      - "8081:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://urlapp:Berny1232@mongodb:27017/urlshortener?authSource=urlshortener
      - SPRING_DATA_MONGODB_DATABASE=urlshortener
      - APP_BASE_URL=https://stellarurl.onrender.com/
      - SERVER_PORT=8080
    depends_on:
      - mongodb
    networks:
      - url-shortener-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=urlapp
      - MONGO_INITDB_ROOT_PASSWORD=Berny1232
      - MONGO_INITDB_DATABASE=urlshortener
    volumes:
      - mongodb-data:/data/db
    networks:
      - url-shortener-network
    command: mongod --auth
    restart: always

volumes:
  mongodb-data:
    driver: local

networks:
  url-shortener-network:
    driver: bridge 