services:
  backend:
    build: .
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://urlapp:your_password_here@mongodb:27017/urlshortener
      - SPRING_DATA_MONGODB_DATABASE=urlshortener
      - APP_BASE_URL=http://localhost:8081/
    depends_on:
      - mongodb
    networks:
      - url-shortener-network

  frontend:
    build: 
      context: ../url-shortener-frontend  # adjust path as needed
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - url-shortener-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=urlapp
      - MONGO_INITDB_ROOT_PASSWORD=your_password_here
      - MONGO_INITDB_DATABASE=urlshortener
      - MONGODB_LOG_VERBOSITY=0
    volumes:
      - mongodb-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - url-shortener-network
    command: mongod --quiet

volumes:
  mongodb-data:

networks:
  url-shortener-network:
    driver: bridge 